[package]
name = "pkgbuild-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
log = "0.4"
nix = { version = "0.27", features = ["fs"] }
tempfile = "3.8"
