[package]
name = "pkgbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
libc = "0.2"
log = "0.4"
nix = { version = "0.27", features = ["fs"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_bytes = { version = "0.11", optional = true }
tempfile = "3.8"

[features]
default = []
format = []
nothread = []
serde = ["dep:serde", "dep:serde_bytes"]

[[example]]
name = "download"
path = "examples/download.rs"
required-features = ["format"]

[[example]]
name = "printsrcinfo"
path = "examples/printsrcinfo.rs"
required-features = ["format"]